# Generated by Django 3.0.5 on 2022-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nome')),
                ('species', models.CharField(max_length=70, verbose_name='Espécie')),
                ('breed', models.CharField(max_length=70, verbose_name='Raça')),
                ('sex', models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], default='Macho', max_length=5, verbose_name='Sexo')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('hair', models.CharField(choices=[('curto', 'curto'), ('longo', 'longo'), ('encaracolado', 'encaracolado'), ('duplo', 'duplo')], default='curto', max_length=12, verbose_name='Pelagem')),
                ('tatoo', models.CharField(blank=True, max_length=7, null=True, verbose_name='Identificação ou Tatuagem')),
            ],
        ),
    ]
